<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Chargehand\Chargehand.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Chargehand.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.Core" Version="2.2.0" />
  </ItemGroup>

</Project>
