<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Chargehand\Chargehand.csproj" />
    <ProjectReference Include="..\Chargehand.OpenCode\Chargehand.OpenCode.csproj" />
    <ProjectReference Include="..\Chargehand.Server\Chargehand.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTelemetry" Version="1.19.1" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.19.1" />
  </ItemGroup>

</Project>
