#!/usr/bin/env python3
"""Regenerate docs/opencode-openapi.json and docs/opencode-api.md from a running OpenCode V2 server.

Usage: OPENCODE_SERVER_PASSWORD=... scripts/gen-opencode-api.py http://127.0.0.1:4096
Auth is HTTP Basic, user "opencode". Only the spec is fetched; no other endpoint is called.
"""
import base64, json, os, sys, urllib.request

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
docs = os.path.join(root, 'docs')

def fetch(url):
    pw = os.environ['OPENCODE_SERVER_PASSWORD']
    req = urllib.request.Request(url.rstrip('/') + '/openapi.json', headers={
        'Authorization': 'Basic ' + base64.b64encode(f'opencode:{pw}'.encode()).decode()})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)

def ref_name(s):
    return s['$ref'].split('/')[-1] if isinstance(s, dict) and '$ref' in s else None

def body_props(spec, op):
    schema = op.get('requestBody', {}).get('content', {}).get('application/json', {}).get('schema', {})
    name = ref_name(schema)
    if name: schema = spec['components']['schemas'][name]
    return sorted(schema.get('properties', {}).keys()), sorted(schema.get('required', []))

def main():
    spec = fetch(sys.argv[1]) if len(sys.argv) > 1 else json.load(open(os.path.join(docs, 'opencode-openapi.json')))
    with open(os.path.join(docs, 'opencode-openapi.json'), 'w') as f:
        json.dump(spec, f, indent=1, sort_keys=True); f.write('\n')
    used = json.load(open(os.path.join(docs, 'opencode-adapter-ops.json')))
    ops = [(m.upper(), p, o) for p, item in spec['paths'].items() for m, o in item.items()]
    out = [f"# OpenCode HTTP API surface\n",
           f"Generated by `scripts/gen-opencode-api.py` from the live spec of an OpenCode server "
           f"(\"{spec['info']['title']}\" {spec['info']['version']}, OpenAPI {spec['openapi']}; adapter pinned to OpenCode "
           f"{used['opencode_version']}). Do not edit by hand.\n",
           f"{len(spec['paths'])} paths, {len(ops)} operations. Declared security schemes: "
           f"{list(spec.get('components', {}).get('securitySchemes', {})) or 'none'}. Observed auth: HTTP Basic, "
           f"user `opencode`, password from `OPENCODE_SERVER_PASSWORD`; every route including `/openapi.json` requires it.\n",
           "## Operations the adapter uses\n",
           "| operation | port method | request body (required*) | responses | mode (observed) | errors seen |",
           "|---|---|---|---|---|---|"]
    for u in used['operations']:
        m, p = u['op'].split(' ', 1)
        o = spec['paths'].get(p, {}).get(m.lower())
        if o is None:
            out.append(f"| `{u['op']}` | {u['port']} | **MISSING FROM SPEC** | | | |"); continue
        props, req = body_props(spec, o)
        body = ', '.join(f'`{x}`' + ('*' if x in req else '') for x in props) or '—'
        codes = ', '.join(sorted(o.get('responses', {})))
        out.append(f"| `{u['op']}` | {u['port']} | {body} | {codes} | {u['mode']} | {', '.join(map(str, u['errors_seen'])) or '—'} |")
    out += ["", "## All operations\n", "| method | path | summary |", "|---|---|---|"]
    for m, p, o in sorted(ops, key=lambda x: (x[1], x[0])):
        out.append(f"| {m} | `{p}` | {o.get('summary', '')} |")
    with open(os.path.join(docs, 'opencode-api.md'), 'w') as f:
        f.write('\n'.join(out) + '\n')

if __name__ == '__main__':
    main()
